# Generated by Django 6.0.3 on 2026-03-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autores_secundarios',
            field=models.ManyToManyField(blank=True, related_name='libros_secundarios', to='biblioteca.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='publicado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
